export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const CLEAR_CART_ITEMS = "CLEAR_CART_ITEMS";

export const CART_ADD_SHIPPING_ADDRESS = "CART_ADD_SHIPPING_ADDRESS";
export const CART_ADD_PAYMENT_METHOD = "CART_ADD_PAYMENT_METHOD";
