export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
export const PRODUCT_DETAILS_RESET = "PRODUCT_DETAILS_RESET";

export const PRODUCT_DELETE_ADMIN_REQUEST = "PRODUCT_DELETE_ADMIN_REQUEST";
export const PRODUCT_DELETE_ADMIN_SUCCESS = "PRODUCT_DELETE_ADMIN_SUCCESS";
export const PRODUCT_DELETE_ADMIN_FAIL = "PRODUCT_DELETE_ADMIN_FAIL";

export const PRODUCT_CREATE_ADMIN_REQUEST = "PRODUCT_CREATE_ADMIN_REQUEST";
export const PRODUCT_CREATE_ADMIN_SUCCESS = "PRODUCT_CREATE_ADMIN_SUCCESS";
export const PRODUCT_CREATE_ADMIN_FAIL = "PRODUCT_CREATE_ADMIN_FAIL";
export const PRODUCT_CREATE_ADMIN_RESET = "PRODUCT_CREATE_ADMIN_RESET";

export const PRODUCT_UPDATE_ADMIN_REQUEST = "PRODUCT_UPDATE_ADMIN_REQUEST";
export const PRODUCT_UPDATE_ADMIN_SUCCESS = "PRODUCT_UPDATE_ADMIN_SUCCESS";
export const PRODUCT_UPDATE_ADMIN_FAIL = "PRODUCT_UPDATE_ADMIN_FAIL";
export const PRODUCT_UPDATE_ADMIN_RESET = "PRODUCT_UPDATE_ADMIN_RESET";
